version: '3.4'

services:
  synapse:
    image: ghcr.io/serverlessworkflow/synapse:latest # Synapse image
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      SYNAPSE_API_HOSTNAME: '${SYNAPSE_HOST}' # The hostname used by Synapse workers to communicate with the server
      SYNAPSE_CLOUDEVENTS_SINK_URI: 'http://${DEMO_HOST}' # The cloud event sink to publish cloud events to. In this simple use-case, Synapse will publish the events directly to the demo service.
    ports:
      - 42286:42286 # Synapse HTTP RESTful API port
      - 41387:41387 # Synapse GRPC API port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mandatory in docker mode, used to spawn worker containers
      #- ./data/definitions:/app/data/definitions # Load demo use-cases
    extra_hosts:
      - host.docker.internal:host-gateway # Mandatory in docker mode, used to communicate with worker containers

  iot-demo:
    image: ${DOCKER_REGISTRY-}synapse-demo
    build:
      context: ../../
      dockerfile: sources/presentation/Synapse.Demo.WebServer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: 'http://+:80'
      HOST: 'http://${DEMO_HOST}'
      CloudEventsSource: 'https://demo.synpase.com'
      CloudEventBroker: 'http://${SYNAPSE_HOST}:42286' # The demo will publish its cloud events directly to Synapse for this simple use-case
      SchemaRegistry: 'https://schema-registry.synapse.com'
    ports:
      - 8088:80
    depends_on:
      - synapse

networks:
  default:
    name: synapse # required by Synapse, used by the workers